# Generated by Django 3.2.9 on 2021-11-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='awards/')),
            ],
        ),
        migrations.CreateModel(
            name='Patners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patmers/')),
                ('image_hover', models.ImageField(upload_to='patmers/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='service/')),
            ],
        ),
    ]
