# Generated by Django 3.2.9 on 2021-11-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0004_awards_patners_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
