# Generated by Django 3.2.9 on 2021-11-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0005_appoinment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoinment',
        ),
    ]
