# Generated by Django 3.2.9 on 2021-11-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0009_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='service/'),
        ),
    ]
