# Generated by Django 3.2.9 on 2021-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0010_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
