# Generated by Django 3.2.9 on 2021-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0011_projectabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='github_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='linkdin_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
